### ISSUE TITLE
Using with Less Compression

### ISSUE THREAD

**Issue by neilchaudhuri** [sbt/sbt-concat#10]
I have a bunch of Less files with sbt-web, and the asset pipeline is compiling the Less files into CSS files and minifying them just fine. However, I am completely unable to get sbt-concat to concatenate the resulting css files.

The original Less files are in app/assets/stylesheets. The resulting files are in public/main/stylesheets.

I configure like this:

pipelineStages := Seq(rjs, concat, digest, gzip)
Concat.groups := Seq(
  "style-group.css" -> group(Seq("stylesheets/myfile.css"))
)

...as well as a ton of other ways including using absolute paths for fun. Nothing has worked.

I have found that I can concatenate other files--but only when I do "activator start" rather than "activator run."

So it seems I have two problems--getting sbt-concat to work when I just run and getting it to pick up CSS files generated from LESS files.

Any insight into what I'm doing wrong is appreciated.

**Comment by acjay** [comment]
@neilchaudhuri @ground5hark  How was this fixed? I'm having the same issue using both `sbt-sass` and `sbt-less`. 

It's not obvious how files are matched when passing a `Seq[String]`, but I also can't get `PathFinder` to work for this either.
