### ISSUE TITLE
Does not work with Play 2.4

### ISSUE THREAD

**Issue by pbn04001** [sbt/sbt-concat#19]
I have tried everything I can think of and no matter what it will not work with Play 2.4.  No exceptions being thrown, just the concatenated file is no where to be found.

I have followed all the steps and am just trying to get this simple example working with no success.  I am running in Dev which is why i have pipelineSages in Assets.

[code]
lazy val webSettings = Seq(
    Concat.groups := Seq(
      "combined.js" -> group(Seq(
        "app/app.js",
        "app/controller/DialogController.js"
      ))
    ),
    pipelineStages in Assets := Seq(concat)
  )
[/code]

**Comment by sebrichards** [comment]
Same issue here.

**Comment by Sergic** [comment]
yes, does not work :(

**Comment by lp-** [comment]
I'm not using play, but I also had the same issue.  No warnings, errors, or output in the target/web folder.  I was using

    addSbtPlugin("net.ground5hark.sbt" %% "sbt-concat" % "0.1.8")

as instructed by the README.md.  But, I realized this version is over a year old.  Actually I think the readme said to use version 0.1.9, but that didn't exist on the binary repo.

Instead, I replaced the addSbtPlugin line with the following and had success:

    lazy val root = (project in file(".")).dependsOn(concatPlugin)
    
    lazy val concatPlugin = uri("https://github.com/ground5hark/sbt-concat.git#342acc34195438799b8a278fda94b126238aae17")

More at http://stackoverflow.com/questions/28924914/in-sbt-how-to-use-addsbtplugin-with-a-github-url/34518385#34518385.

**Comment by eximius313** [comment]
+1

**Comment by andrey-chorniy** [comment]
+1
Please deploy 0.1.9

**Comment by mgosk** [comment]
I use sbt-concat with Play 2.5 and it works fine for me

**Comment by mkurz** [comment]
Outdated, works in Play 2.8 projects for me.
Also will release a new version of sbt-concat in the next minutes which upgrades all dependencies and changes groupId.
