### ISSUE TITLE
Project including sbt-concat can no longer use sbteclipse plugin.

### ISSUE THREAD

**Issue by applitect** [sbt/sbt-concat#25]
We have an angular project where we use sbt-concat. After including the plugin, we can no longer use sbt eclipse as there is an incompatible version of scalaz included with the old version of sbt-web used with the latest release of this plugin. The sbt-web plugin needs updated.

**Comment by applitect** [comment]
Pull request made.

**Comment by eximius313** [comment]
+1

**Comment by jroper** [comment]
This is now using the latest sbt-web, so I guess is fixed now.
