### ISSUE TITLE
Upgrade for SBT 1.0 and Play 2.6

### ISSUE THREAD

**Issue by eximius313** [sbt/sbt-concat#30]
In order to use this plugin in Play 2.6 and SBT 1.0, it needs to be upgraded.
see: https://github.com/playframework/playframework/issues/7045 and https://github.com/playframework/playframework/issues/7261

**Comment by dwijnand** [comment]
sbt 1 was done in https://github.com/sbt/sbt-concat/pull/32

Closing under the optimistic assumption that that (or another PR) solved the Play 2.6 part.
