### ISSUE TITLE
0.2.0 tag missing

### ISSUE THREAD

**Issue by dwijnand** [sbt/sbt-concat#34]
Looks like sbt-compat 0.2.0 is out: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/net.ground5hark.sbt/sbt-concat/scala_2.12/sbt_1.0/0.2.0/

But there's no tag.

@jroper do you have that tag locally?  Otherwise we can try and reconstruct which commit it was built from.

**Comment by jroper** [comment]
Sorry, I think the release process failed halfway through, and I manually completed the release, but forgot to complete the git side of things. I've pushed the tag now.
