### ISSUE TITLE
Relative paths in CSS

### ISSUE THREAD

**Issue by dribba** [sbt/sbt-concat#4]
I have a few CSS files with relative paths to other resources(images, fonts), I'm using the plugin to concatenate all the css, including some form webjars.  
Taken from Font Awesome:
@font-face{font-family:'FontAwesome';src:url('../fonts/fontawesome-webfont.eot?v=4.1.0')

Since the path to the css changes, all the relative paths stop working.
I know the easy fixes are either just copy those resources to the appropriate place, but that would be hard to keep track of; or edit the paths, which is not always possible if using webjars.

**Comment by ioRekz** [comment]
What does your groups look like when concat. webjars assets ? Can't find the src path

**Comment by eximius313** [comment]
@dribba how do you use ```sbt-concat``` with files included in ```WebJars```?

**Comment by dribba** [comment]
@eximius313 I opened this issue 2 years ago, I don't worn in the project that needed this anymore, not sure if web-jars has fixed it, but if not, here's a repo that you can use as a guide to build an sbt plugin to update relative to absolute urls: https://github.com/neomaclin/sbt-simple-url-update
